development:
  adapter: postgresql
  encoding: unicode
  database: yelp_development
  pool: 5
  port: 5432
  username: 'mikhailkryukov'
  password: 'postgres'

test:
  adapter: postgresql
  encoding: unicode
  database: yelp_test
  pool: 5
  username: 'mikhailkryukov'
  password: 'postgres'